wireplumber.components = [
  {
    name = wavedevicefix.lua,
    type = script/lua
    provides = custom.wave1fix,
    arguments = { device = "wave1" }
  }
]

wireplumber.profiles = {
  main = {
    custom.wave1fix = required
  }
}

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Elgato_Systems_Elgato_Wave_1_*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Elgato_Systems_Elgato_Wave_1_*"
      }
    ]
    actions = {
      update-props = {
        node.name = "wave1-source"
      }
    }
  }
]