wireplumber.components = [
  {
    name = wavedevicefix.lua,
    type = script/lua
    provides = custom.xlrdockfix,
    arguments = { device = "xlrdock" }
  }
]

wireplumber.profiles = {
  main = {
    custom.wave3fix = required
  }
}

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Elgato_Systems_Elgato_XLR_Dock*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Elgato_Systems_Elgato_XLR_Dock*"
      }
    ]
    actions = {
      update-props = {
        node.name = "xlrdock-source"
      }
    }
  }
]